# fly.toml app configuration file generated for wheres-waldo-8123 on 2023-10-14T03:33:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wheres-waldo-8123"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
